temp-dir: /tmp/midi-ripper
sound:
  #  name: "USB Audio CODEC: - (hw:1,0)"
  device-name: "Scarlett 2i4 USB: Audio (hw:1,0)"
  channels: 2 
  sample-rate: 48000
  # sample-rate: 96000
  max-peak-volume: 0.99
  min-peak-volume: 0.09
midi:
  # name: "JD-Xi:JD-Xi MIDI 1 24:0"
  device-name: "Scarlett 2i4 USB:Scarlett 2i4 USB MIDI 1 20:0"
  # Mido numbers channels 0 to 15 instead of 1 to 16.
  # This makes them easier to work with in Python but you may want to add and subtract 1 when communicating with the user.
  channel: 0
  velocities:
      - 100
  duration: 15
  sustain-time: 10
  decay-time: 5
  pitch-ranges:  # http://newt.phys.unsw.edu.au/jw/notes.html
    bass:
      lowest-pitch: 21    # A0
      highest-pitch: 60   # C4
    piano:
      lowest-pitch: 21    # A0
      highest-pitch: 107  # B7
    synth:
      lowest-pitch: 36    # C2
      highest-pitch: 88   # E6
  pitch-step: 1
logger:
  name: "midi-ripper"
  filename: "log.midi-ripper"
